const customers = [
  {
    _id: '1',
    fName: 'Ahmadjon1',
    lName: 'Polonchiyev1',
    mName: 'Polonchi ogli',
    image: '/images/customers/profile1.jpg',
    dob: '12/31/1987',
    cityBorn: 'Rishton',
    pasportNum: 'AA9991199',
    pasportIssuedBy: 'Rishton IIB',
    pasportIssuedAt: '12/31/2015',
    pasportExpAt: '12/31/2025',
    addressStreet: '12 Muhayyir st',
    addressCity: 'Rishton',
    addressProvince: 'Fergona',
    addressZIP: 151300,
    phoneNum: '91-998-98-77',
    email: 'abc@gmail.com',
    position: 'Doktor',
    workAt: 'Kasalxona # 1',
    salary: 2000000,
    rating: '95%',
    description: 'Tez-Tibbiy bolimda ishlaydi',
  },
  {
    _id: '2',
    fName: 'Ahmadjon2',
    lName: 'Polonchiyev2',
    mName: 'Polonchi ogli',
    image: '/images/customers/profile1.jpg',
    dob: '12/31/1987',
    cityBorn: 'Rishton',
    pasportNum: 'AA9991199',
    pasportIssuedBy: 'Rishton IIB',
    pasportIssuedAt: '12/31/2015',
    pasportExpAt: '12/31/2025',
    addressStreet: '12 Muhayyir st',
    addressCity: 'Rishton',
    addressProvince: 'Fergona',
    addressZIP: 151300,
    phoneNum: '91-998-00-77',
    email: 'abc@gmail.com',
    position: 'Xamshira',
    workAt: 'Kasalxona # 1',
    salary: 2000000,
    rating: '95%',
    description: 'Tez-Tibbiy bolimda ishlaydi, Pistonchini qushnisi',
  },
  {
    _id: '3',
    fName: 'Ahmadjon3',
    lName: 'Polonchiyev3',
    mName: 'Polonchi ogli',
    image: '/images/customers/profile1.jpg',
    dob: '12/31/1987',
    cityBorn: 'Rishton',
    pasportNum: 'AA9991199',
    pasportIssuedBy: 'Rishton IIB',
    pasportIssuedAt: '12/31/2015',
    pasportExpAt: '12/31/2025',
    addressStreet: '12 Muhayyir st',
    addressCity: 'Rishton',
    addressProvince: 'Fergona',
    addressZIP: 151300,
    phoneNum: '91-998-98-78',
    email: 'abc@gmail.com',
    position: 'Suvchi',
    workAt: 'Kasalxona # 1',
    salary: 2000000,
    rating: '95%',
    description: 'Tez-Tibbiy bolimda ishlaydi, Pistonchini qushnisi',
  },
  {
    _id: '4',
    fName: 'Ahmadjon4',
    lName: 'Polonchiyev4',
    mName: 'Polonchi ogli',
    image: '/images/customers/profile1.jpg',
    dob: '12/31/1987',
    cityBorn: 'Rishton',
    pasportNum: 'AA9991199',
    pasportIssuedBy: 'Rishton IIB',
    pasportIssuedAt: '12/31/2015',
    pasportExpAt: '12/31/2025',
    addressStreet: '12 Muhayyir st',
    addressCity: 'Rishton',
    addressProvince: 'Fergona',
    addressZIP: 151300,
    phoneNum: '91-998-98-77',
    email: 'abc@gmail.com',
    position: 'Xamshira',
    workAt: 'Kasalxona # 1',
    salary: 2000000,
    rating: '95%',
    description: 'Tez-Tibbiy bolimda ishlaydi, Pistonchini qushnisi',
  },
  {
    _id: '5',
    fName: 'Ahmadjon5',
    lName: 'Polonchiyev5',
    mName: 'Polonchi ogli',
    image: '/images/customers/profile1.jpg',
    dob: '12/31/1987',
    cityBorn: 'Rishton',
    pasportNum: 'AA9991199',
    pasportIssuedBy: 'Rishton IIB',
    pasportIssuedAt: '12/31/2015',
    pasportExpAt: '12/31/2025',
    addressStreet: '12 Muhayyir st',
    addressCity: 'Rishton',
    addressProvince: 'Fergona',
    addressZIP: 151300,
    phoneNum: '91-998-98-77',
    email: 'abc@gmail.com',
    position: 'Xamshira',
    workAt: 'Kasalxona # 1',
    salary: 2000000,
    rating: '95%',
    description: 'Tez-Tibbiy bolimda ishlaydi, Pistonchini qushnisi',
  },
]

export default customers
